language: python

sudo: required

python:
  - "2.7"

env:
- SET_CI=1

services:
  - mongodb
  - redis-server

before_script:
  - sleep 15
  - mongo mydb_test --eval 'db.addUser("travis", "test");'

install:
  - pip install -r requirements.txt
  - pip install django==1.9.5

script: python manage.py test