version: '2'
services:
  postgresDb:
    image: postgres:9.5
    environment:
      - POSTGRES_PASSWORD=bigguy
      - POSTGRES_USER=postgres
    volumes:
      - ./postgresDB/data/:/var/lib/postgresql/data/
      - ./postgresDB/log/:/var/log/postgresql
      - ./postgresDB/config/:/etc/postgresql
    ports:
      - "5432:5432"

  python2:
    image: iamforeverme/python2:1
    volumes:
    - ./crawls/:/src/
    working_dir: /src/jobSpiders/

  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/src
    ports:
      - "8000:8000"

    depends_on:
      - postgresDb

