version: '2'
services:
  mongodb:
    image: mongo:3.2
    environment:
     - "--auth"
    volumes:
     - ./mongo/data/:/data/db/
    ports:
      - "27017:27017"
#    command: --auth

  redis:
    image: redis:3
    volumes:
    - ./redis/data/:/data/
    ports:
      - "6379:6379"
#  crawls:
#    build: .
#    command: scrapy crawl jobSpiders
#    volumes:
#      - ./crawler/jobSpiders/:/src
#    depends_on:
#      - mongodb
#    ports:
#      - "8080:8080"

  web:
    build: .
    command: bash -c "supervisord ; python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/src
      - ./supervisord/:/etc/supervisor/
      - ./log/:/var/log/supervisor/
    ports:
      - "8000:8000"
      - "9001:9001"
    depends_on:
      - mongodb
      - redis
