# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-30 13:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobInfo', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='jobModel',
            new_name='JobInfo',
        ),
    ]
