//search condition
export const CHANGE_KEYWORD = "CHANGE_KEYWORD";
export const CHANGE_LOCATION = "CHANGE_LOCATION";
export const CHANGE_PERIOD = "CHANGE_PERIOD";
//TODO: multi keywords
// export const ADD_KEYWORD = "ADD_KEYWORD";
// export const DELETE_KEYWORD = "DELETE_KEYWORD";

//query
export const QUERY_JOB_REQUEST = "QUERY_JOB_REQUEST";
export const QUERY_JOB_SUCCESS = "QUERY_JOB_SUCCESS";
export const QUERY_JOB_ERROR = "QUERY_JOB_ERROR";
export const UPDATE_JOB_DATA = "UPDATE_JOB_DATA";

export const QUERY_INCOME_REQUEST = "QUERY_INCOME_REQUEST";
export const QUERY_INCOME_SUCCESS = "QUERY_INCOME_SUCCESS";
export const QUERY_INCOME_ERROR = "QUERY_INCOME_ERROR";
export const UPDATE_INCOME_DATA = "UPDATE_INCOME_DATA";
